== Terms and definitions

This document uses the terms defined in https://portal.ogc.org/public_ogc/directives/directives.php[OGC Policy Directive 49], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this Standard and OGC documents do not use the equivalent phrases in the ISO/IEC Directives, Part 2.

This document also uses terms defined in the OGC Standard for Modular specifications (https://portal.opengeospatial.org/files/?artifact_id=34762[OGC 08-131r3]), also known as the 'ModSpec'. The definitions of terms such as standard, specification, requirement, and conformance test are provided in the ModSpec.

The following additional terms and definitions also apply.


=== Node
The "thing" that collects and transmits data. Typically at the remote site, such as a weather station. This would be a device such as a datalogger or a sensor.

=== Hub
The software at the central server that receives data from the Node and prepares it for further processing. It must be able to receive the data using the agreed Data Format and Protocol.

=== Protocol
The IP based set of rules that determine how data is transferred from the Node to the Hub.

=== Data Format
A data format is the organisation of information according to specifications. It defines how the data is structured and encoded.

=== Data Serialization
The process of converting structured data into a Data Format that can be easily transmitted and reconstructed later.

=== Data Schema
A formal description in the declarative language defining the structure and constraints for the Data Format.

=== Observation
A single measurement data point collected by the Node, such as a temperature reading, humidity level, or wind speed.

=== Metadata
Additional information, such as the monitoring site ID, location, types of sensors, measured variables, measurement units, and other relevant details. It provides context for the data being transmitted.

=== Abbreviated terms

.Symbols and abbreviated terms
|===
|Abbreviation |Term

|CF
|Climate and Forecast (CF) Metadata Conventions

|HMEI
|HydroMeteorological and Environmental Industry

|MQP
|Message Queuing Protocol

|MQTT
|Message Queuing Telemetry Transport

|PubSub
|Publish / Subscribe

|QoS
|Quality of Service

|URI
|Uniform Resource Identifier

|URL
|Uniform Resource Locator

|WIS
|WMO Information System

|WMO
|World Meteorological Organization

|===
