name: validate schema and examples

on:
  push:
    paths:
      - '**.proto'
  pull_request:
    paths:
      - '**.proto'

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v5
      name: Setup Python ${{ matrix.python-version }}
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies 📦
      run: |
        sudo apt-get install protobuf-compiler
    - name: Install requirements 📦
      run: |
        python3 -m pip install --upgrade pip
        pip3 install protobuf
    - name: Generate Python code
      run: |
        mkdir generated
        protoc -I . --python_out=generated schemas/first-mile-message-encoding.proto 
        ls -l generated/schemas
